# Generated by Django 4.2.4 on 2023-08-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'Movies', 'verbose_name_plural': 'Movies'},
        ),
    ]
