# Generated by Django 4.2.4 on 2023-08-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='number_of_tickets',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
